self.lineEdit_consommation_par_unite_de_temps_firstRow.setPlaceholderText("Entrez la consommation par unité de temps (valeur finale)")
self.lineEdit_total_qty.setPlaceholderText("Total quantité calculée (résultat final)")
self.lineEdit_tests_par_conditionnment_secondRow.setPlaceholderText("Nombre de tests par conditionnement (valeur clé)")
self.lineEdit_total_calibration_volume.setPlaceholderText("Volume total calibré (donnée essentielle)")
self.lineEdit_total_loss.setPlaceholderText("Pertes totales enregistrées (à surveiller)")
self.lineEdit_qte_total_confirmation_fiveRow.setPlaceholderText("Quantité totale confirmée (vérifiez ici)")
self.lineEdit_qte_cm_ajustee_sixRow.setPlaceholderText("Quantité ajustée (CM - valeur optimisée)")
self.lineEdit_qte_a_commander_sixRow.setPlaceholderText("Quantité à commander (action requise)")